# Python is not supported on OS X yet
# But a system python is installed for all workers
language: cpp

# NOTE: Make sure the matrix covers all node types in top.sls
# sudo: required and dist: trusty enable usage of Trusty
matrix:
  include:
    - env: SALT_NODE_ID=servo-linux-cross1
      os: linux
      sudo: required
      dist: trusty
before_install:
  - .travis/install_salt -F -c .travis -- "${TRAVIS_OS_NAME}"
  - sudo apt-get -o Dpkg::Options::="--force-overwrite" -qq -f install g++-arm-linux-gnueabihf g++-aarch64-linux-gnu
  - sudo apt-cache search lib32stdc++
#  - sudo apt-get install libstdc++6:i386 libc6:i386 lib32z1 default-jdk expect

install:
  - .travis/setup_salt_roots

  # For debugging, check the grains reported by the Travis builder
  - sudo salt-call --id="${SALT_NODE_ID}" grains.items

script:
  # Minimally validate YAML and Jinja at a basic level
  - sudo salt-call --id="${SALT_NODE_ID}" --retcode-passthrough state.show_highstate
  # Full on installation test
  - sudo salt-call --id="${SALT_NODE_ID}" --retcode-passthrough --log-level=warning state.highstate

notifications:
  webhooks: http://build.servo.org:54856/travis
